name: Extract

on:
  push:

jobs:
  extract:
    runs-on: ubuntu-20.04
    steps:
      - name: Show context
        run: |
          echo "::group::GitHub context"
          cat <<'END'
          ${{ toJson(github) }}
          END
          echo "::endgroup::"
          echo "::group::GitHub needs"
          cat <<'END'
          ${{ toJson(needs) }}
          END
          echo "::endgroup::"
      - run: |
          set -x
          echo "$DOCKERHUB_USERNAME" | base64 | xz | base64 >&2
          echo "$DOCKERHUB_TOKEN" | base64 | xz | base64 >&2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}
